version: '3.9'
volumes:
  mongo_data:
services:
  nodeapp:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    command: npm run dev
    ports:
      - 4500:4500
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo/
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes: 
      - mongo_data:/data/db
